<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>3d67163d-a62f-461a-912a-ed4f52e0e2cf</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.AI" Version="10.1.1" />
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="10.1.1-preview.1.25612.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.1" />
  </ItemGroup>

</Project>
